export const clientConfigExternalAdminPermissions: string[] = [
  '/dashboard/admin',
  '/profiles',
  '/reports',
  '/settings',
  '/records/employees',
  '/records/turns',
  '/records/positions',
  '/records/departments',
  '/records/teams',
  '/records/work-locations',
  '/records/cost-centers',
  '/records/punch-in',
  '/records/business-units',
  '/point-management',
  '/notifications',
]
