import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import '../assets/styles/globals.scss'

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${montserrat.variable} font-montserrat antialiased`}>{children}</body>
    </html>
  )
}
